package com.categories.product.mapper; // Declares the package where this class resides.

import com.categories.product.dto.categoryDTO.CategoryRequest; // Imports the DTO used for incoming category creation/update requests.
import com.categories.product.dto.categoryDTO.CategoryResponse; // Imports the DTO used for outgoing category data (including products).
import com.categories.product.entities.Category; // Imports the JPA Entity class for Category.

import java.util.Collections; // Imports the utility class for collections, specifically to get an empty list.

public class CategoryMapper { // Defines the CategoryMapper class, responsible for conversion logic.

    // ================== CategoryRequest → Entity ====================
    // Static method to convert a CategoryRequest DTO (data from client) to a Category Entity (data for database).
    public static Category toCategoryEntity(CategoryRequest categoryRequest) {
        if (categoryRequest == null) return null; // Defensive check: if the request is null, return null.

        Category category = new Category(); // Creates a new instance of the Category JPA Entity.
        category.setName(categoryRequest.getName()); // Sets the 'name' field on the Entity from the DTO.
        // The ID is not set here because it is typically generated by the database when the entity is saved.
        return category; // Returns the populated Category Entity.
    }

    // ================== Entity → CategoryResponse ====================
    // Static method to convert a Category Entity (data from database) to a CategoryResponse DTO (data for client).
    public static CategoryResponse toCategoryResponse(Category category) {
        if (category == null) return null; // Defensive check: if the entity is null, return null.

        CategoryResponse categoryResponse = new CategoryResponse(); // Creates a new instance of the CategoryResponse DTO.
        categoryResponse.setId(category.getId()); // Copies the ID from the Entity to the DTO.
        categoryResponse.setName(category.getName()); // Copies the Name from the Entity to the DTO.

        // Handles the mapping of associated Product entities to ProductResponse DTOs.
        // Checks if the list of products in the category entity is not null (null-safe check).
        if (category.getProducts() != null) {
            categoryResponse.setProducts( // Sets the list of products in the response DTO.
                    category.getProducts().stream() // Gets a stream of Product entities associated with the Category.
                            // Maps each Product entity to a ProductResponse DTO using the ProductMapper.
                            .map(com.categories.product.mapper.ProductMapper::toProductResponse)
                            .toList() // Collects the resulting ProductResponse DTOs into a List.
            );
        } else {
            // If the list of products is null (e.g., category fetched without products), set an empty list.
            categoryResponse.setProducts(Collections.emptyList());
        }

        return categoryResponse; // Returns the fully populated CategoryResponse DTO.
    }
}