package com.categories.product.mapper; // Declares the package where this class resides.

import com.categories.product.dto.productDTO.ProductRequest; // Imports the DTO for incoming product data (create/update).
import com.categories.product.dto.productDTO.ProductResponse; // Imports the DTO for outgoing product data (response).
import com.categories.product.entities.Category; // Imports the Category JPA Entity class, needed for setting the association.
import com.categories.product.entities.Product; // Imports the Product JPA Entity class.

public class ProductMapper { // Defines the ProductMapper class, responsible for conversion logic.

    // Entity ----> ProductResponse
    // Static method to convert a Product Entity (data from database) to a ProductResponse DTO (data for client).
    public static ProductResponse toProductResponse(Product product) {
        // Creates and returns a new ProductResponse object, assuming ProductResponse has an all-arguments constructor.
        return new ProductResponse(
                product.getId(), // Maps the Product ID.
                product.getName(), // Maps the Product Name.
                product.getDescription(), // Maps the Product Description.
                product.getPrice(), // Maps the Product Price.
                // Accesses the associated Category entity and maps only its ID to the response.
                product.getCategory().getId()
        );


    }

    // ProductRequest ----> Entity
    // Static method to convert a ProductRequest DTO to a Product Entity.
    // Takes the DTO and the retrieved Category Entity as input.
    public static Product toProductEntity(ProductRequest productResponse , Category category) {
        Product product = new Product(); // Creates a new instance of the Product JPA Entity.

//        product.setId(productResponse.getId());  // Comment indicating that the ID should not be set manually.
//        --> ID is automatically generated by the database upon saving.
        product.setName(productResponse.getName()); // Sets the Name from the DTO.
        product.setDescription(productResponse.getDescription()); // Sets the Description from the DTO.
        product.setPrice(productResponse.getPrice()); // Sets the Price from the DTO.
        product.setCategory(category); // Sets the association by linking the retrieved Category Entity.
        return product; // Returns the populated Product Entity, ready to be saved.


    }


}